version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # The root username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: example # The root password for MongoDB

  springboot:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGODB_AUTH_DB: admin # The authentication database for MongoDB
      MONGODB_DB: school # The database name for the application
      MONGODB_PORT: 27017 # The port on which MongoDB is running
      MONGODB_HOST: mongo # The hostname for the MongoDB service
    depends_on:
      - mongo # The springboot service depends on the mongo service