version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  springboot:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGODB_AUTH_DB: admin
      MONGODB_DB: school
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo
    depends_on:
      - mongo