name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -e -X

      - name: Run unit tests
        run: mvn test -e -X

      - name: Run integration tests
        run: mvn failsafe:integration-test -e -X

      - name: Run Cucumber tests
        run: mvn test -Dcucumber.options="--plugin pretty" -e -X