name: CI/CD Pipeline - JMeter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker run -d --name jmeter-container -v ${{ github.workspace }}:/workspace -w /workspace openjdk:11-jdk-slim tail -f /dev/null

      - name: Install JMeter
        run: |
          docker exec jmeter-container apt-get update
          docker exec jmeter-container apt-get install -y wget
          docker exec jmeter-container wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          docker exec jmeter-container tar -xzf apache-jmeter-5.4.1.tgz
          docker exec jmeter-container mv apache-jmeter-5.4.1 /opt/jmeter
          docker exec jmeter-container ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter

      - name: Verify JMeter Test Plan Path
        run: docker exec jmeter-container ls -la /workspace/src/test/resources/performance/get-api-performance-test-plan.jmx

      - name: Run JMeter Tests for GET
        run: |
          docker exec jmeter-container jmeter -n -t /workspace/src/test/resources/performance/get-api-performance-test-plan.jmx -l results-get.jtl

      - name: Verify JTL File for GET
        run: |
          head -n 1 results-get.jtl
          if ! grep -q "timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect" results-get.jtl; then
            echo "Error: results-get.jtl is missing required columns" >&2
            exit 1
          fi

      - name: Upload Results for GET
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-get
          path: results-get.jtl

      - name: Install Latency Lingo CLI
        run: |
          curl -L https://github.com/latency-lingo/cli/releases/latest/download/latency-lingo-cli_linux_amd64.tar.gz | tar -xz

      - name: Analyze Results for GET with Latency Lingo
        run: |
          set -e
          ./latency-lingo-cli publish --file "results-get.jtl" --api-key "${{ secrets.LATENCY_LINGO_API_KEY }}" --label "GET API Performance Test Plan" --format "jmeter" --env "production" > output.log || { cat output.log; exit 1; }
          result=$(grep "Test run status" output.log | awk '{print $6}')
          echo "result=$result" >> $GITHUB_OUTPUT
        env:
          LATENCY_LINGO_API_KEY: ${{ secrets.LATENCY_LINGO_API_KEY }}