name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run unit tests
        run: mvn test

      - name: Run integration tests
        run: mvn failsafe:integration-test

      - name: Run Cucumber tests
        run: mvn test -Dcucumber.options="--plugin pretty"

    # - name: Code quality check
    #   run: mvn sonar:sonar
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # - name: Build Docker image
    #   run: docker build -t myapp:${{ github.sha }} .

    # - name: Push Docker image
    #   run: docker push myapp:${{ github.sha }}
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Deploy to Kubernetes
    #   run: kubectl apply -f k8s/deployment.yaml
    #   env:
    #     KUBECONFIG: ${{ secrets.KUBECONFIG }}