##name: CI/CD Pipeline
##
##on:
##  push:
##    branches:
##      - master
##  pull_request:
##    branches:
##      - master
##
##jobs:
##  build:
##    runs-on: ubuntu-latest
##
##    steps:
##      - name: Checkout code
##        uses: actions/checkout@v4
##
##      - name: Set up JDK 17
##        uses: actions/setup-java@v4
##        with:
##          java-version: '17'
##          distribution: 'temurin'
##
##      - name: Build with Maven
##        run: mvn clean install -e -X
##
##      - name: Run unit tests
##        run: mvn test -e -X
##
##      - name: Run integration tests
##        run: mvn failsafe:integration-test -e -X
##
##      - name: Run Cucumber tests
##        run: mvn test -Dcucumber.options="--plugin pretty" -e -X
#
#name: CI/CD Pipeline
#
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    services:
#      mongo:
#        image: mongo:latest
#        ports:
#          - 27017:27017
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#
#      - name: Wait for MongoDB to start
#        run: |
#          for i in `seq 1 30`; do
#            nc -z localhost 27017 && echo "MongoDB is up" && exit 0
#            echo "Waiting for MongoDB..."
#            sleep 1
#          done
#          echo "MongoDB did not start in time" && exit 1
#
#      - name: Build with Maven
#        run: mvn clean install -e -X
#
#      - name: Run unit tests
#        run: mvn test -e -X
#
#      - name: Run integration tests
#        run: mvn failsafe:integration-test -e -X
#
#      - name: Run Cucumber tests
#        run: mvn test -Dcucumber.options="--plugin pretty" -e -X

name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set environment variables
        run: |
          echo "MONGODB_AUTH_DB=admin" >> $GITHUB_ENV
          echo "MONGODB_DB=school" >> $GITHUB_ENV
          echo "MONGODB_PORT=27017" >> $GITHUB_ENV
          echo "MONGODB_HOST=localhost" >> $GITHUB_ENV

      - name: Wait for MongoDB to start
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 27017 && echo "MongoDB is up" && exit 0
            echo "Waiting for MongoDB..."
            sleep 1
          done
          echo "MongoDB did not start in time" && exit 1

      - name: Build with Maven
        run: mvn clean install -e -X

      - name: Run unit tests
        run: mvn test -e -X

      - name: Run integration tests
        run: mvn failsafe:integration-test -e -X

      - name: Run Cucumber tests
        run: mvn test -Dcucumber.options="--plugin pretty" -e -X