name: CI/CD Pipeline - JMeter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set environment variables
        run: |
          echo "MONGODB_AUTH_DB=admin" >> $GITHUB_ENV
          echo "MONGODB_DB=school" >> $GITHUB_ENV
          echo "MONGODB_PORT=27017" >> $GITHUB_ENV
          echo "MONGODB_HOST=localhost" >> $GITHUB_ENV

      - name: Wait for MongoDB to start
        run: |
          for i in `seq 1 60`; do
            nc -z localhost 27017 && echo "MongoDB is up" && exit 0
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB did not start in time" && exit 1

      - name: Check MongoDB logs
        run: docker logs $(docker ps -q --filter ancestor=mongo:latest)

      - name: Build with Maven
        run: mvn clean install -e -X

      - name: Set up Docker
        run: |
          docker run -d --name jmeter-container -v ${{ github.workspace }}:/workspace -w /workspace openjdk:11-jdk-slim tail -f /dev/null

      - name: Install JMeter
        run: |
          docker exec jmeter-container apt-get update
          docker exec jmeter-container apt-get install -y wget
          docker exec jmeter-container wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
          docker exec jmeter-container tar -xzf apache-jmeter-5.4.1.tgz
          docker exec jmeter-container mv apache-jmeter-5.4.1 /opt/jmeter
          docker exec jmeter-container ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter

      - name: Start REST API
        run: |
          docker exec -d jmeter-container java -jar target/*.jar

      - name: Install curl
        run: |
          docker exec jmeter-container apt-get update
          docker exec jmeter-container apt-get install -y curl

      - name: Wait for Spring Boot to start
        run: |
          for i in `seq 1 60`; do
            docker exec jmeter-container curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' && echo "Spring Boot is up" && exit 0
            echo "Waiting for Spring Boot..."
            sleep 1
          done
          echo "Spring Boot did not start in time"
          docker logs jmeter-container --tail 100
          exit 1

      - name: Verify JMeter Test Plan Path
        run: docker exec jmeter-container ls -la /workspace/src/test/resources/performance/get-api-performance-test-plan.jmx
      - name: Run JMeter Tests for GET
        run: |
          docker exec jmeter-container jmeter -n -t /workspace/src/test/resources/performance/get-api-performance-test-plan.jmx -l results-get.jtl

      - name: Verify JTL File for GET
        run: |
          head -n 1 results-get.jtl
          if ! grep -q "timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect" results-get.jtl; then
            echo "Error: results-get.jtl is missing required columns" >&2
            exit 1
          fi

      - name: Upload Results for GET
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-get
          path: results-get.jtl

      - name: Install Latency Lingo CLI
        run: |
          curl -L https://github.com/latency-lingo/cli/releases/latest/download/latency-lingo-cli_linux_amd64.tar.gz | tar -xz

      - name: Analyze Results for GET with Latency Lingo
        run: |
          set -e
          ./latency-lingo-cli publish --file "results-get.jtl" --api-key "${{ secrets.LATENCY_LINGO_API_KEY }}" --label "GET API Performance Test Plan" --format "jmeter" --env "production" > output.log || { cat output.log; exit 1; }
          result=$(grep "Test run status" output.log | awk '{print $6}')
          echo "result=$result" >> $GITHUB_OUTPUT
        env:
          LATENCY_LINGO_API_KEY: ${{ secrets.LATENCY_LINGO_API_KEY }}